version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c '
      ./wait-for-it.sh db:5432 -- yarn add npx prisma generate && yarn start'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql://alexandre:lalalab@db:5432/mini?schema=public"
      REDIS_URL: redis://redis:6379

  db:
    image: postgres:latest
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: alexandre
      POSTGRES_PASSWORD: lalalab
      POSTGRES_DB: mini
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
  subscriber:
    build:
      context: ./miniFactory
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "db:5432", "--", "yarn", "start"]
    depends_on:
      - redis



volumes:
  postgres_data:
